### ISSUE TITLE
Adding to vector fails after 32 elements, if created from empty seq

### ISSUE THREAD

**Issue by Vindaar** [PMunch/nim-persistent-vector#1]
I just stumbled upon a bug in my `ggplotnim` code, which caused me to create a `PersistentVector` from an empty sequence. In effect something like the following:
```nim
let vec = toPersistentVector(newSeq[int]())
```

Adding elements to this vector at first works just fine, but fails after 32 elements. We then get stuck here in the loop, since `n` is already `0`: 
https://github.com/PMunch/nim-persistent-vector/blob/master/persvector.nim#L70-L71.

Code to reproduce the bug:
```nim
import persvector, sequtils

let data = toSeq(0 .. 32)
var vector = toPersistentVector(newSeq[int]())
for i, x in data:
  echo "Adding ", x, " at ", i
  vector = vector.add x # on last iteration we get stuck here
  echo "Vector ", vector
```

Although I guess we should not get stuck in that while loop, a simple fix would of course be to have `toPersistentVector` check the length of the argument `seq` and in case it's empty just call `initVector`.

**Comment by PMunch** [comment]
It seems to have actually been caused by the `shifts` and/or `tree` fields to be initialised as if the vector had data. I pushed a fix that should leave you with essentially the same thing as calling `initVector` would give you when the length is 0.

**Comment by Vindaar** [comment]
Cool, thanks! :)
